modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/Tki-sor/Upd8r/issues"

[[mods]]
modId = "upd8r"
version = "${version}"
displayName = "upd8r"
logoFile = "icon.png"
authors = "Tki_sor"
description = '''
More Powerful Modpack Update Check Mod.
'''

[[dependencies.upd8r]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.upd8r]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.upd8r]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
